### ISSUE TITLE
Edit Displayed Text in Bug List Filters

### ISSUE THREAD

**Issue by Niloth-p** [Niloth-p/glitch-guru#1]
Edit the text displayed by the bug type filter and the bug status filter in the ListView of Bug Hub.
The filters are not displaying the human-friendly name currently.

**Comment by Paul-Annay** [comment]
@Niloth-p can I try this?

**Comment by Niloth-p** [comment]
> @Niloth-p can I try this?

Yep, just got to edit the bug list template in 2 places.

The code already uses the friendly names of bug type and status in other places and templates, so use that as a reference.

Let me know if you need any help.

**Comment by harsha-mangena** [comment]
@Niloth-p , Can you assign me this issue.

**Comment by GajendraR** [comment]
can i work on this issue

**Comment by harsha-mangena** [comment]
@Niloth-p Please find the below PR:https://github.com/Niloth-p/glitch-guru/pull/13

**Comment by Niloth-p** [comment]
> can i work on this issue

Hey, Harsha's working on this one. 
Hang tight, I will create some new modular issues the following week.
