### ISSUE TITLE
Enhance Alert Messages for 'Library Not Loading' Errors

### ISSUE THREAD

**Issue by Niloth-p** [Niloth-p/glitch-guru#2]
The alerts generated when certain libraries from CDNs are not being loaded - just show something like
"<library name> is not loading - some features may not work"
Edit that to make it more user-friendly.

These alerts are generated from the base template.
See GlitchGuru/templates/base.html
Currently, all the libraries call the same helper function, hence the alert is not customized apart from using the library name.

Tell the user 
- which features are likely to be affected
- why the library is probably not loading
- whether it's something to worry about or ignore

**Comment by Teja-11** [comment]
can you assign this task to me
