### ISSUE TITLE
Persistent Search Term in Search Bar on Searching

### ISSUE THREAD

**Issue by Niloth-p** [Niloth-p/glitch-guru#3]
On searching, as a refresh occurs, the search bar is reloaded and cleared.
The search term should be displayed on the search bar.

Get the search term from the URL query parameter, and edit the search bar element in Bug Hub's list template.

**Comment by jepoy92** [comment]
Can i get assigned to this issue!

**Comment by Monika-Tiyyagura** [comment]
@Niloth-p Hey can i take up the issue? I had worked on the similar issue!!

**Comment by Niloth-p** [comment]
Hi @Monika-Tiyyagura! Sure, please feel free to submit a PR.

**Comment by Tumaki88** [comment]
hey can i be assigned here. I have past experience related to this.

**Comment by Niloth-p** [comment]
I'm not assigning anybody to the issue. It's an extremely straight forward tiny change, anyone is welcome to submit a PR. It does not require any kind of expertise.
