### ISSUE TITLE
Replace the bug view button with an eye icon

### ISSUE THREAD

**Issue by Niloth-p** [Niloth-p/glitch-guru#5]
## Description
Replace the blue view button in the actions column of the list page, with an eye icon from FontAwesome.

## Tasks
- The blue view button should be removed from the bug list template.
- The FontAwesome eye icon (using the fa-eye class) should be added in its place.

## Additional Information
You don't have to include the fontawesome library (or register yourself at Fontawesome), the library is already linked.

**Comment by choidf** [comment]
Could I contribute to this issue?

**Comment by minhify** [comment]
.take

**Comment by shvmsrc** [comment]
Hi, can I please take this issue ?

**Comment by Niloth-p** [comment]
It's straightforward and changes needed only in 1 file, so anyone can directly submit a PR.
